<?php

namespace Helkiper\StatisticBundle\Repository;

/**
 * VisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitRepository extends \Doctrine\ORM\EntityRepository
{
//return  $this->createQueryBuilder('t')
//->select('count(t.id) as c')
//->where('t.category = :category_id')
//->setParameter('category_id', $categoryId)sawdefgffdffffff2e1wzzdrfrfffdxxxxxdsaaq
//->setMaxResults(1)
//->getQuery,()
//->getSingleScalarResult();aqaawaaaashjkjhwqw3wesEETFSEDVVSW35GHUKJ.,

	public function getVisitedBrowserCount(){
		return $this->createQueryBuilder('v')
			->select('count(v.id) as c, v.browser as b')
			->addGroupBy('v.browser')
			->getQuery()
			->getResult();
	}
}
