comment_index:
    path:     /
    defaults: { _controller: "HelkiperBlogBundle:Comment:index" }
    methods:  GET

comment_new:
    path:     /new
    defaults: { _controller: "HelkiperBlogBundle:Comment:new" }
    methods:  [GET, POST]
