helkiper_blog_category:
    resource: "@HelkiperBlogBundle/Resources/config/routing/category.yml"
    prefix:   /category

helkiper_blog_post:
    resource: "@HelkiperBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

helkiper_blog_homepage:
    path:     /
    defaults: { _controller: HelkiperBlogBundle:Default:index }
