<?php

namespace Helkiper\BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCommentsInCategory($categoryId){
		return  $this->createQueryBuilder('c')
			->where('c.category = :category_id')
			->setParameter('category_id', $categoryId)
			->getQuery()
			->getResult();

	}

	public function getCommentsInPost($postId){
		return  $this->createQueryBuilder('c')
			->where('c.post = :post_id')
			->setParameter('post_id', $postId)
			->getQuery()
			->getResult();

	}
}
