<?php

namespace Helkiper\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPostsInCategory($categoryId){
		return  $this->createQueryBuilder('p')
			->where('p.category = :category_id')
			->setParameter('category_id', $categoryId)
			->getQuery()
			->getResult();

	}
}
